site_name: NTCIP SMI
site_description: NTCIP Structure of Management Information
repo_url: https://github.com/ite-org/NTCIP-8004
nav:
  - Front Matter:
      - Title Page: index.md
      - Notices: notices.md
      - Acknowledgements: acknowledgements.md
      - Foreword: foreword.md
      - Introduction: introduction.md
  - 1 General: general.md
  - 2 Background: background.md
  - 3 Object Identification: object-identification.md
  - 4 Rules for Module Development: rules-for-module-development.md
  - 5 Requirements for Implementations: requirements-for-agent-implementations.md
  - 6 Guidelines for Agencies: guidelines-for-operating-agencies.md
  - A NTCIP SMI: smi.md
  - B Conversion to SMIv2: conversion.md
  - C Macro Examples: macro-examples.md
  - D History of Changes: history-of-changes.md
site_url: https://ite-org.github.io/NTCIP-8004/
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://github.com/ite-org/NTCIP-8004">NTCIP SMI</a> by <span property="cc:attributionName">NTCIP</span> is licensed under <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1" alt=""></a></p>
theme:
  name: material
  features:
    - content.code.copy
    - content.status
    - content.tooltips
    - icons
    - navigation.path
    - navigation.top
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
    admonition:
      question: fontawesome/solid/comments
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css
  - stylesheets/pdf.css
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
plugins:
  - search
  - git-revision-date-localized:
      type: date
  - to-pdf:
      author: "AASHTO / ITE / NEMA"
      copyright: "CC-BY-4.0 (https://creativecommons.org/licenses/by/4.0/)"
      cover_logo: images/NTCIP.jpg
      cover_subtitle: "https://ite-org.github.io/NTCIP-8004/latest/"
      enabled_if_env: "EXPORT_PDF"
      output_path: pdf/NTCIP-8004.pdf
      download_link: header
      ordered_chapter_level: 0
  - mermaid2:
      arguments:
        theme: |
            ^(window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches) ? 'dark' : 'light'
        securityLevel: loose
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - meta
  - footnotes
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      auto_append:
        - resources/glossary.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
extra:
  search:
    highlight: true
  hide:
    - title
  version:
    provider: mike
    alias: true
    default: latest
